# Generated by Django 4.2.7 on 2023-11-25 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetModels',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
        migrations.CreateModel(
            name='UploadModels',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dataset', models.FileField(null=True, upload_to='')),
                ('File_size', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upload_dataset',
            },
        ),
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('username', models.TextField(max_length=25, null=True)),
                ('contact', models.TextField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.TextField(max_length=8, null=True)),
                ('file', models.FileField(null=True, upload_to='images')),
                ('user_status', models.TextField(default='pending', max_length=30, null=True)),
                ('Otp_Status', models.TextField(default='pending', max_length=20)),
                ('otp', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
