# Generated by Django 4.2.7 on 2023-11-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='username',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UserFeedbackModels',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_feedback', models.TextField(max_length=900)),
                ('star_rating', models.CharField(max_length=100, null=True)),
                ('star_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sentment', models.TextField(max_length=20, null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodels')),
            ],
            options={
                'db_table': 'feedback_Details',
            },
        ),
    ]
